### ISSUE TITLE
license of dataset

### ISSUE THREAD

**Issue by ohashi3399** [LAION-AI/AIW#1]
Hi!
I appreciate for sharing this great dataset!
I couldn't find any descriptions about the license of dataset.
Could you provide it?

I would be glad if you will point out if you've already made public.
Thanks!

**Comment by JeniaJitsev** [comment]
Hey @ohashi3399 - license for the whole repo, including any collected data presented here, is Apache 2.0, we made it explicit in README.md. Hope this resolves it.
